[tool.poetry]
name = "daschland-scripts"
version = "0.1.0"
description = ""
authors = ["danielasubotic <48174709+danielasubotic@users.noreply.github.com>", "noemivillars-amberg <117180458+Notheturtle@users.noreply.github.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dsp-tools = "^8.1.0.post18"
icecream = "^2.1.3"
pillow = "^10.3.0"
pymediainfo = "^6.1.0"
pyexiftool = "^0.5.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
