[tool.poetry]
name = "daschland-scripts"
version = "0.1.0"
description = ""
authors = ["danielasubotic <48174709+danielasubotic@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dsp-tools = "^7.1.3.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
